# Generated by Django 3.0.5 on 2021-06-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/Student/'),
        ),
    ]
